In [1]:
import pandas as pd
import numpy as np

In [2]:
result_path = 'data\college result.csv'
KIE_path = 'data\kauffman startup index.csv'
college_df = pd.read_csv(result_path, encoding = 'utf-8')
KIE_df = pd.read_csv(KIE_path)
#college_df.head()

In [3]:
KIE_df['Category'].unique()

array(['National', 'Large', 'Small', 'MSA'], dtype=object)

In [4]:
state_bool = (KIE_df['Category'] == 'Large') | (KIE_df['Category'] == 'Small')
year_state_bool = state_bool & (KIE_df['Index Year'] == 2015)
#KIE_df.loc[state_bool, 'Location_name' ].unique()

KIE_filtered = KIE_df.loc[year_state_bool, :]

In [16]:
KIE_filtered.sort_values('Location_name').head()
KIE_filtered['cur_index'] = KIE_filtered['index_last_y'] + KIE_filtered['index_diff']
#KIE_filtered.loc[:, ['cur_index', 'Location_name']].sort_values('cur_index', ascending = False)

KIE_sorted = KIE_filtered.loc[:, ['cur_index', 'Location_name']].sort_values('cur_index', ascending = False)
KIE_sorted.columns = ['cur_index', 'state']

C:\Users\Michael\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [20]:
def above75perc (index):
    if index > 0.57:
        return True
    else:
        return False
    
KIE_sorted['above75'] = KIE_sorted['cur_index'].map(above75perc)

In [21]:
KIE_sorted

      cur_index           state  above75
1418       3.43         Montana     True
1481       1.30          Nevada     True
509        1.11          Alaska     True
773        1.11         Florida     True
2072       0.99           Texas     True
663        0.99        Colorado     True
887        0.92           Idaho     True
618        0.85      California     True
1110       0.65       Louisiana     True
2106       0.64            Utah     True
842        0.64          Hawaii     True
2328       0.63         Wyoming     True
1794       0.58        Oklahoma     True
2111       0.54         Vermont    False
1991       0.47    South Dakota    False
1618       0.47        New York    False
1714       0.40    North Dakota    False
1603       0.37      New Mexico    False
524        0.12         Arizona    False
1345      -0.27     Mississippi    False
708       -0.39        Delaware    False
1657      -0.42  North Carolina    False
1446      -0.82        Nebraska    False
1123      -0.98           Maine    False
1958      -0.99  South Carolina    False
1070      -1.01        Kentucky    False
1388      -1.11        Missouri    False
1021      -1.13          Kansas    False
1193      -1.19        Maryland    False
931       -1.20        Illinois    False
577       -1.26        Arkansas    False
818       -1.36         Georgia    False
1763      -1.45            Ohio    False
1199      -1.52   Massachusetts    False
694       -1.53     Connecticut    False
2163      -1.64        Virginia    False
2214      -1.65      Washington    False
1838      -1.65          Oregon    False
1272      -1.70        Michigan    False
1544      -1.70      New Jersey    False
1916      -1.71    Rhode Island    False
974       -2.22            Iowa    False
1526      -2.33   New Hampshire    False
970       -2.38         Indiana    False
2030      -2.44       Tennessee    False
2262      -2.80   West Virginia    False
476       -3.04         Alabama    False
1880      -3.22    Pennsylvania    False
1306      -3.42       Minnesota    False
2281      -3.83       Wisconsin    False

In [6]:
KIE_df['Index Year'].sort_values().unique()

array([ 1977.,  1978.,  1979.,  1980.,  1981.,  1982.,  1983.,  1984.,
        1985.,  1986.,  1987.,  1988.,  1989.,  1990.,  1991.,  1992.,
        1993.,  1994.,  1995.,  1996.,  1997.,  1998.,  1999.,  2000.,
        2001.,  2002.,  2003.,  2004.,  2005.,  2006.,  2007.,  2008.,
        2009.,  2010.,  2011.,  2012.,  2013.,  2014.,  2015.,  2016.,
        2017.,    nan])

In [7]:
KIE_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3869 entries, 0 to 3868
Data columns (total 29 columns):
year_CPS                    3840 non-null float64
Characteristic              399 non-null object
OppShare_New_Entrp          1587 non-null float64
Breakdown                   399 non-null object
Rate_New_Entrp              1709 non-null float64
Location                    3869 non-null int64
startup_index               21 non-null float64
Index Year                  3859 non-null float64
year_BDS                    3460 non-null float64
startup_density             3460 non-null float64
Rank                        1224 non-null float64
Composition_of_New_Entrp    399 non-null float64
norm_rate                   1331 non-null float64
norm_opp                    1245 non-null float64
norm_density                3441 non-null float64
z_rate                      1331 non-null float64
z_oppshare                  1245 non-null float64
z_startup_den               3460 non-null float64
rank_last_y                 1134 non-null float64
rank_diff                   1134 non-null float64
index_last_y                1154 non-null float64
index_diff                  1154 non-null float64
dataset                     3859 non-null object
Location_name               3869 non-null object
Category                    3869 non-null object
OppShare_New_Entrp_web      1587 non-null float64
Rate_New_Entrp_web          1709 non-null float64
location_category           3869 non-null object
index_diff_text             3869 non-null object
dtypes: float64(21), int64(1), object(7)
memory usage: 876.6+ KB

In [25]:
KIE_df.loc[0, :]

month                              12
grdatn                             42
marstat                             5
age                                57
class                               4
region                              1
state                              14
hours                              40
mlr                                 1
natvty                             57
msafp                           49340
msastat                             2
faminc                             15
spneth                             -1
race                                1
year                             2014
class_t1                            4
mlr_t1                              1
wgta                          3032.98
ind2                             8190
indmaj2                            10
ind2_t1                          8190
indmaj2_t1                         10
pid            15866200851 3111 11912
yeart1                           2015
female                              1
immigr                              0
homeown                           NaN
hoursu1b                           40
hoursu1b_t1                        40
se15u                               0
se15u_t1                            0
ent015u                             0
ent015ua                            0
vet                                 0
wgtat                         269.172
wgtat1                        270.434
Name: 0, dtype: object